name: Go Continuous Intergration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Build Application
        run: go build

      - name: Deploy Application
        run: go run main.go
